linux:
  hosts:
  children:
    rocky:
      hosts:
        10.0.5.75:
          hostname: rocky-1
          lan_ip: 10.0.5.10
        10.0.5.76:
          hostname: rocky-2
          lan_ip: 10.0.5.11
        10.0.5.77:
          hostname: rocky-3
          lan_ip: 10.0.5.12
      vars:
        device: ens34

  vars:
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7xz79FtFAyExvJFI7dPh2IZqr+3jM5FfsGQbtS2sZOjrTUKPUnRDHiCb/N9cZev2610KII0aQsfO1TZER6Rj6dyQVGVaLcYEqA/PagaHABOOpugsxw5WC0O/k4x5Bgq+TOnTFEQhmCQ/aYMjANSXzMPjGkkONdP30HGTosBGhoYXf9U0OkfLatIY+XQMsey75zk9Gvo/bKwv5FXn0TrTjUg/Yua/OvSDKJBCvO+Q+KTRa6B37FV51As2iloCoYIbiS7NGciA/IPCPyK5rXpBYz2X7U1Xth1lrWAwL5nzmR64gqwnC8CEHc65YOTMQM3CJoHVUaobv+jmsxDKT1IANePLJqMDfGHZEF0hidSaK6zILt8keiXyFj4Hbggc73NdwWVd5YRUQENPwAxKH5UW8nhL6YSEMd1nRHRqL2tFfELX6NkHen5fpQ4Y6WVTHC0R2B5Rd0kAeZHvLmf9B02IUiJ8/u0QaaAdErB1x/QRZSBuWYTj12e5XHZYB0TDT3vs= deployer@480-mgmt-luc"
    ansible_user: deployer
    prefix: 24
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue7.local