# Usage: ansible-playbook -i inventories/linux.yaml --ask-pass rocky-playbook.yml -K
- name: rocky config
  hosts: rocky
  tasks:
  - name: Create the .ssh directory  if it doesn't exist
    file:
      path: "/home/{{ ansible_user }}/.ssh"
      state: directory
      mode: 0700

  - name: Create authorized_keys file
    file:
      path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
      state: touch
      mode: 0644

  - name: Copy key block and add to authorized_keys
    blockinfile:
      dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
      block: "{{ public_key }}"

# NOTE: The "Create sudoers drop in file for 480" and "Create a dropin entry 
# for /etc/sudoers.d/480" tasks kept giving me a timeout error. Instead of using those, I ran 
# sudo visudo /etc/sudoers.d/480 and put 'deployer ALL=(ALL) NOPASSWD: ALL' without quotes on 
# both boxes. I then saved the file and removed the s udoers.d content from my playbooks 
# and ran them again. This was the only way that I could get things to work. In retrospect, 
# I would have done this before taking a base snapshot so that the new clones that are being 
# created have a passwordless ansible user built in and ready to go. If you have to do this too, 
# make sure your remove the "Create sudoers drop in file for 480" and "Create a dropin entry 
# for /etc/sudoers.d/480" tasks from this playbook, then save and run it with the command
# provided at the top of this file. 

  - name: Create sudoers drop in file for 480
    file:
      path: /etc/sudoers.d/480
      state: touch
      mode: 0440
    become: yes

  - name: Create a dropin entry for /etc/sudoers.d/480
    blockinfile:
      dest: /etc/sudoers.d/480
      block: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    become: yes

  - name: Set the hostname
    hostname:
      name: "{{ hostname }}"
    become: yes
  
  - name: Add host to file
    lineinfile:
      path: /etc/hosts
      line: '127.0.1.1 {{ hostname }}'
    become: yes

  - name: Run nmcli
    #nmcli connection modify ens34 ipv4.address 10.0.5.10/24 ipv4.gateway 10.0.5.2 ipv4.dns '10.0.5.5 10.0.5.2' ipv4.method manual
    nmcli:
      conn_name: "{{device}}"
      ip4: "{{lan_ip}}/24"
      gw4: "{{gateway}}"
      state: present
      type: ethernet
      dns4:
        - "{{name_server}}"
        - "{{gateway}}"
      method4: manual
    become: yes

  - name: Bounce the box
    shell: "sleep 5 && shutdown -r"
    become: yes
    async: 1
    poll: 0
  